title: Chakradhaar Viswatmula # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  M.S. Business Analytics at The University of Illinois at Chicago 
  <br><br>
  B.Tech. Computer Science at PES University, Bangalore, India
  <br><br>
  <a href="https://www.linkedin.com/in/chakradhaar/">My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
