title: Chakradhaar Viswatmula
logo: "/assets/images/headshot.png?raw=true"
description: >
  <br><br>
  Experience
  <br> &ensp;
  <a href="https://www.americanexpress.com/">
    <img src="/assets/images/AXP_BlueBoxLogo_Alternate_REGULARscale_RGB_DIGITAL_700x700.png?raw=true" style="width:42px;height:42px;">
  </a> &ensp;
  <a href="https://www.conduent.com/">
    <img src="/assets/images/Conduent_logo.svg.png?raw=true" style="width:123px;height:32px;">
  </a> &ensp;
  <br><br>
  Education
  <br>
  <a href="/assets/documents/diploma">
    M.S. Business Analytics <br> University of Illinois Chicago
  </a>
  <br><br>
  B.Tech. Computer Science <br> PES University, Bangalore, India
  <br><br>
  Certifications
  <br> &ensp;
  <a href="/assets/documents/tf_cert">
    <img src="/assets/images/tf_badge.png?raw=true" style="width:42px;height:42px;">
  </a> &ensp;
  <a href="/assets/documents/google_da">
    <img src="/assets/images/google_logo.png?raw=true" style="width:32px;height:32px;">
  </a> &ensp;
  <a href="/assets/documents/tableau_cert">
    <img src="/assets/images/tableau-logo.png?raw=true" style="width:32px;height:32px;">
  </a>
  <br>
  Links
  <br> &ensp;
  <a href="https://www.linkedin.com/in/chakradhaarrv/">
    <img src="/assets/images/linkedin-logo.png?raw=true" style="width:28px;height:28px;">
  </a> &ensp;
  <a href="https://github.com/chakradhaarrv">
    <img src="/assets/images/github-logo.png?raw=true" style="width:28px;height:28px;">
  </a> &ensp;
  <a href="mailto:crviswatmula@gmail.com">
    <img src="/assets/images/gmail.png?raw=true" style="width:28px;height:28px;">
  </a>
  <br><br>
  

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
google_analytics: UA-000000-0
